# ---
# {{- $apiV1 := false -}}
# {{- $apiVersion := "extensions/v1beta1" -}}
# {{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= v1.19.0-0" .Capabilities.KubeVersion.Version) -}}
#   {{- $apiVersion = "networking.k8s.io/v1" -}}
#   {{- $apiV1 = true -}}
# {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
#   {{- $apiVersion = "networking.k8s.io/v1beta1" -}}
# {{- else -}}
#   {{- $apiVersion = "extensions/v1beta1" -}}
# {{- end }}
# apiVersion: {{ $apiVersion }}
# kind: Ingress
# metadata:
#   name: "{{ .Chart.Name }}-ingress"
#   annotations:
#     {{ if .Values.global.certManager.enabled }}
#     cert-manager.io/cluster-issuer: {{.Values.global.certManager.name}}
#     {{ end }}
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/proxy-buffering: "on"
#     nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
#     nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
#     # Snippet directives are disabled by the Ingress administrator
#     # nginx.ingress.kubernetes.io/configuration-snippet: |
#     #   server_tokens off;

# spec:
#   tls:
#   - hosts:
#       - {{.Values.appConfig.ingressUrl}}
#     secretName: {{.Values.appConfig.certificateName}}
#   rules:
#     - host: {{.Values.appConfig.ingressUrl}}
#       http:
#         paths:
#           - path: /
#             {{- if $apiV1 }}
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: "{{ .Chart.Name }}-service"
#                 port:
#                   number: {{.Values.service.port}}
#             {{- else }}
#             backend:
#               serviceName: "{{ .Chart.Name }}-service"
#               servicePort: {{.Values.service.port}}
#             {{- end }}

