---
{{ if .Values.appConfig.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ if .Values.global.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{.Values.global.certManager.name}}
    {{ end }}
    kubernetes.io/ingress.class: traefik
#    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-basic-auth@kubernetescrd
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.appConfig.ingressUrl }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 8888
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.appConfig.ingressUrl }}
      secretName: {{ .Release.Name }}-{{ .Chart.Name }}-tls
{{ end }}
