---
apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}-service"
  labels:
    service-label-key: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: "{{ .Chart.Name }}-selector"
