spring:
  application:
    name: hive-connect-server

  security:
    oauth2:
      client:
        registration:
          hive-connect-client:
            client-id: hive-connect-client
            client-secret: 8c53cfa7-5c6f-4e34-9e29-4c3c95d8c965
            authorization-grant-type: client_credentials
            scope: fhir/*.read,fhir/*.write
