spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hiveconnect
    username: hiveconnect
    password: hiveconnect
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
