apiVersion: v1
stringData:
  jdbc-uri: jdbc:postgresql://develop-hive-connect-postgres-openfhir:5432/openfhir?password=postgres&user=openfhir
  password: postgres
  username: openfhir
kind: Secret
metadata:
  name: develop-hive-connect-postgres-openfhir-secret
