apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: postgres
          image: "postgres:latest"  # You can specify a specific version
          env:
            {{- if .Values.useExternalSecrets }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.secretName }}
                  key: {{ .Values.externalSecrets.usernameKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.secretName }}
                  key: {{ .Values.externalSecrets.postgresPasswordKey }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecrets.secretName }}
                  key: {{ .Values.externalSecrets.databaseKey }}
            {{- else }}
            - name: POSTGRES_USER
              value: {{ .Values.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.auth.password }}
            - name: POSTGRES_DB
              value: {{ .Values.auth.database }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
