apiVersion: v2
name: hive-connect
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: hiveconnect
    version: 0.1.0
  - name: openfhir
    version: 0.1.0
  - name: ehrbase
    version: 0.1.0
  - name: postgres-ehrbase
    version: 0.1.0
  - name: postgres-hiveconnect
    version: 0.1.0
  - name: postgres-openfhir
    version: 0.1.0
  - name: postgres-hapi
    version: 0.1.0
  - name: hapi-fhir-jpaserver
    version: 0.14.0
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    alias: hapi-fhir

