name: hive-connect
replicaCount: 1

global:
  certManager:
    enabled: false
  postgresql:
    servicePort: 5432
  ehrBase:
    hostName: ehrbase
  openFHIR:
    enabled: true
    hostName: openfhir
    port: 8090

imagePullSecrets:
  - name: imagepullsecret-github-packages

container:
  image: ghcr.io/highmed-ev/hive-connect
  pullPolicy: Always
  resources: { }
  environment:
    profile: deploy
    sqlDialect: org.hibernate.dialect.PostgreSQLDialect

appConfig:
  bootstrapdir: /app/templates
  serverUrl: http://develop-hapi-fhir:8080/fhir
  postgresqlDatabase: hiveconnect
  postgresqlUsername: hiveconnect
  postgresqlPassword: password
  postgresqlDatabaseSecretName: develop-hive-connect-postgres-hiveconnect-secret
  databaseServiceName: develop-hive-connect-postgres-hiveconnect
  version: develop
  enabled: true
  ingressUrl: hive-connect.develop.de
  environment:
    ehrbaseUsername: ehrbase
    ehrbasePassword: ehrbase
    ehrbaseAuthAdminUser: ehrbaseAdmin
    ehrbaseAuthAdminPassword: ehrbaseAdmin
  keycloakUrl: http://keycloak-http
  keycloakRealm: realmName
  authenticationType: "basic"
  basicUsername: username
  basicPassword: password
  demographicsPatientUrl: https://demographics-service
  terminologyServerUrl: https://terminology-server
  fhirValidationOptionalIdentifier: true
  forceUpdate: true
  certificateName: hiveconnect-certificate
  clientssl:
    keystorepass: keystorepass
    truststorepass: truststorepass
    enabled: "true"
    keypassword: keypassword
    keystore: /etc/hiveconnect/keystore.p12
    keystoretype: pkcs12
    truststore: /etc/hiveconnect/truststore.p12
    truststoretype: pkcs12
service:
  enabled: true
  port: 8888
  type: ClusterIP


openfhir:
  global:
    env: env
  name: openfhir
  replicaCount: 1
  storage:
    storageClass: ssd
  container:
    image: ghcr.io/medblocks/openfhir
    tag: main
    pullPolicy: Always
    resources: {}
  appConfig:
    version: 1.3.0
    ingressUrl: openfhir
    postgresqlDatabase: openfhir
    postgresqlDatabaseSecretName: postgres-openfhir-secret
    env:
      DB_TYPE: postgres
      BOOTSTRAP_RECURSIVELY_OPEN_DIRECTORIES: true
  ingress: 
    enabled: false
    host: 
  imagePullSecrets:
    - name: imagepullsecret-github-packages
  service:
    enabled: true
    port: 8090
    type: ClusterIP


postgres-openfhir:
  auth:
    postgresPassword: postgres
    username: openfhir
    password: postgres
    database: openfhir

  primary:
    persistence:
      enabled: true
      size: 1Gi

  service:
    type: ClusterIP


postgres-hiveconnect:
  auth:
    postgresPassword: postgres
    username: hiveconnect
    password: postgres
    database: hiveconnect

  primary:
    persistence:
      enabled: true
      size: 1Gi

  service:
    type: ClusterIP
