apiVersion: v1
stringData:
  jdbc-uri: jdbc:postgresql://develop-hive-connect-postgres-ehrbase:5432/ehrbase?password=postgres&user=postgres
  password: postgres
  username: postgres
kind: Secret
metadata:
  name: {{ .Values.name}}-postgres-ehrbase-secret

