# Enable external secrets (default: false)
useExternalSecrets: false

# Database Credentials
auth:
  postgresPassword: postgres
  username: hapi
  password: postgres
  database: hapi

# Persistent Volume Settings
primary:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ssd

# Service Configuration
service:
  type: ClusterIP  # Change to LoadBalancer or NodePort for external access
  port: 5432
  targetPort: 5432

# External Secrets Configuration (only used when useExternalSecrets is true)
externalSecrets:
  secretName: postgres-hapi-secrets
  usernameKey: username
  passwordKey: password
  databaseKey: database
  postgresPasswordKey: postgresPassword
