apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-keystore-volume"
  labels:
    app: "{{ .Values.name }}-keystore-volume"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
binaryData:
  keystore.p12: |-
    {{ .Files.Get "certs/keystore.p12" | b64enc}}
  truststore.p12: |-
    {{ .Files.Get "certs/truststore.p12" | b64enc}}
